init structure
ToxicDoges/Memesis pull request #1
Opened 2023-10-03 16:23 UTC by psy667

2023-10-03 16:30 UTC, nickbiryukov approved these changes

2023-10-04 16:50 UTC, Zenderg approved these changes

2023-10-04 18:53 UTC, alexeytashmatov requested changes

2023-10-04 18:53 UTC, alexeytashmatov commented on README.md
> +git clone https://github.com/ToxicDoges/Memesis.git
\```bash
git clone https://github.com/ToxicDoges/Memesis.git
\```

2023-10-04 18:53 UTC, alexeytashmatov commented on services/caption_generator.go
Предлагаю заюзать структуру как предлагается на сайте го https://go.dev/doc/modules/layout
![image](https://github.com/ToxicDoges/Memesis/assets/98321551/c04ae135-173d-49ee-bde3-55b1d48bdc4b)
 Хотя и так тоже ок, но мне кажется что может быть больше чем один файл в модуле, например тот же тест
 Просто предложение к рассмотрению)
 @Zenderg @nickbiryukov что думаете?

2023-10-04 20:33 UTC, psy667 commented on README.md
> +git clone https://github.com/ToxicDoges/Memesis.git
fixed

2023-10-04 20:34 UTC, psy667 commented on services/caption_generator.go
сделал, сервер перенес в /cmd также как в той доке, плюс добавил директорию bin

2023-10-04 20:39 UTC, alexeytashmatov approved these changes

2023-10-05 12:16 UTC, merged